[DB-AG] Online_Kredit/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _DB_AG__Online_Kredit.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

[DB-AG] Online_Kredit/Controllers/KreditController.cs
using _DB_AG__Online_Kredit.BusinessLogic;
using _DB_AG__Online_Kredit.Models;
using KreditFreigabe;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _DB_AG__Online_Kredit.Controllers
{
    public class KreditController : Controller
    {
        [HttpGet]
        public ActionResult KreditRechner()
        {
            Debug.WriteLine("HttpGet: Kredit/KreditRechner");

            KreditRechnerModel model = new KreditRechnerModel()
            {
                KreditBetrag = 25000,  
                Laufzeit = 12  
            };
            int k_id = -1;
            if (Request.Cookies["id"] != null && int.TryParse(Request.Cookies["id"].Value, out k_id))
            {
                KreditWunsch wunsch = KreditVerwaltung.KreditLaden(k_id);
                model.KreditBetrag = (int)wunsch.Betrag;
                model.Laufzeit = wunsch.Laufzeit;
            }


            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult KreditRechner(KreditRechnerModel model)
        {
            Debug.WriteLine("HttpPost: Kredit/KreditRechner");

            if (ModelState.IsValid)
            {

                if (Request.Cookies["id"] == null)
                {

                    Kunde newKunde = KreditVerwaltung.ErzeugeKunde();

                    if (newKunde != null && KreditVerwaltung.KreditSpeichern(model.KreditBetrag, model.Laufzeit, newKunde.ID))
                    {
                        Response.Cookies.Add(new HttpCookie("id", newKunde.ID.ToString()));
                        return RedirectToAction("FinanzielleSituation");
                    }
                }
                else
                {
                    int idKunde = int.Parse(Request.Cookies["id"].Value);

                    if (KreditVerwaltung.KreditSpeichern(model.KreditBetrag, model.Laufzeit, idKunde))
                    {
                        return RedirectToAction("Zusammenfassung");
                    }
                }

            }

            return View(model);

        }



        [HttpGet]
        public ActionResult FinanzielleSituation()
        {
            Debug.WriteLine("HttpGet: Kredit/FinanzielleSituation");

            FinanzielleSituationModel model = new FinanzielleSituationModel()
            {
                ID_Kunde = int.Parse(Request.Cookies["id"].Value)
            };


            FinanzielleSituation situation = KreditVerwaltung.FinanzielleSituationLaden(model.ID_Kunde);
            if (situation != null)
            {
                model.EinkuenfteAlimenteUnterhalt = (double)situation.EinkuenfteAlimenteUnterhalt.Value;
                model.MonatsEinkommenNetto = (double)situation.MonatsEinkommenNetto.Value;
                model.Raten = (double)situation.Raten.Value;
                model.AusgabenAlimenteUnterhalt = (double)situation.AusgabenAlimenteUnterhalt.Value;
                model.Wohnkosten = (double)situation.Wohnkosten.Value;
            }


            return View(model);
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult FinanzielleSituation(FinanzielleSituationModel model)
        {

            Debug.WriteLine("HttpPost: Kredit/FinanzielleSituation");

            if (ModelState.IsValid)
            {
                if (KreditVerwaltung.FinanzielleSituationSpeichern(
                                                model.MonatsEinkommenNetto,
                                                model.Raten,
                                                model.Wohnkosten,
                                                model.EinkuenfteAlimenteUnterhalt,
                                                model.AusgabenAlimenteUnterhalt,
                                                model.ID_Kunde))
                {
                    if (Request.Cookies["zsmid"] != null)
                    {
                        return RedirectToAction("Zusammenfassung");

                    }
                    return RedirectToAction("Arbeitgeber");
                }
            }

            return View(model);
        }



        [HttpGet]
        public ActionResult Arbeitgeber()
        {
            Debug.WriteLine("HttpGet: Kredit/Arbeitgeber");

            List<BeschaeftigungModel> alleBeschaeftigungen = new List<BeschaeftigungModel>();
            List<BrancheModel> alleBranchen = new List<BrancheModel>();

            foreach (var branche in KreditVerwaltung.BranchenLaden())
            {
                alleBranchen.Add(new BrancheModel()
                {
                    ID = branche.ID.ToString(),
                    Bezeichnung = branche.Bezeichnung
                });
            }

            foreach (var beschaeftigung in KreditVerwaltung.BeschaeftigungenLaden())
            {
                alleBeschaeftigungen.Add(new BeschaeftigungModel()
                {
                    ID = beschaeftigung.ID.ToString(),
                    Bezeichnung = beschaeftigung.Bezeichnung
                });
            }

            ArbeitgeberModel model = new ArbeitgeberModel()
            {
                AlleBeschaeftigungen = alleBeschaeftigungen,
                AlleBranchen = alleBranchen,
                ID_Kunde = int.Parse(Request.Cookies["id"].Value)
            };

            Arbeitgeber arbeitgeberDaten = KreditVerwaltung.ArbeitgeberLaden(model.ID_Kunde);
            if (arbeitgeberDaten != null)
            {
                model.BeschaeftigungSeit = arbeitgeberDaten.BeschaeftigtSeit.Value.ToString("MM.yyyy");
                model.Firma = arbeitgeberDaten.Firma;
                model.ID_BeschaeftigungsArt = arbeitgeberDaten.FKBeschaeftigungsArt; ;
                model.ID_Branche = arbeitgeberDaten.FKBranche.Value;
            }


            return View(model);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Arbeitgeber(ArbeitgeberModel model)
        {
            Debug.WriteLine("HttpPost: Kredit/Arbeitgeber");

            if (ModelState.IsValid)
            {
                if (KreditVerwaltung.ArbeitgeberSpeichern(
                                                model.Firma,
                                                model.ID_BeschaeftigungsArt,
                                                model.ID_Branche,
                                                model.BeschaeftigungSeit,
                                                model.ID_Kunde))
                {
                    if (Request.Cookies["zsmid"] != null)
                    {
                        return RedirectToAction("Zusammenfassung");

                    }
                    return RedirectToAction("PersönlicheDaten");
                }
            }
            return View();
        }





        [HttpGet]
        public ActionResult PersönlicheDaten()
        {
            Debug.WriteLine("HttpGet: Kredit/PersönlicheDaten");

            List<BildungsModel> alleBildungsAngaben = new List<BildungsModel>();
            List<FamilienstandModel> alleFamilienStandAngaben = new List<FamilienstandModel>();
            List<IdentifikationsModel> alleIdentifikationsangaben = new List<IdentifikationsModel>();
            List<StaatsbuergerschaftsModel> alleStaatsbuergerschaftsAngaben = new List<StaatsbuergerschaftsModel>();
            List<TitelModel> alleTitelAngaben = new List<TitelModel>();
            List<WohnartModel> alleWohnartAngaben = new List<WohnartModel>();

            foreach (var bildungsAngabe in KreditVerwaltung.BildungsangabenLaden())
            {
                alleBildungsAngaben.Add(new BildungsModel()
                {
                    ID = bildungsAngabe.ID.ToString(),
                    Bezeichnung = bildungsAngabe.Bezeichnung
                });
            }

            foreach (var familienStand in KreditVerwaltung.FamilienstandLaden())
            {
                alleFamilienStandAngaben.Add(new FamilienstandModel()
                {
                    ID = familienStand.ID.ToString(),
                    Bezeichnung = familienStand.Bezeichnung
                });
            }
            foreach (var Identifikationsangabe in KreditVerwaltung.IdentifikationsangabenLaden())
            {
                alleIdentifikationsangaben.Add(new IdentifikationsModel()
                {
                    ID = Identifikationsangabe.ID.ToString(),
                    Bezeichnung = Identifikationsangabe.Bezeichnung
                });
            }
            foreach (var land in KreditVerwaltung.LaenderLaden())
            {
                alleStaatsbuergerschaftsAngaben.Add(new StaatsbuergerschaftsModel()
                {
                    ID = land.ID,
                    Bezeichnung = land.Bezeichnung
                });
            }
            foreach (var titel in KreditVerwaltung.TitelLaden())
            {
                alleTitelAngaben.Add(new TitelModel()
                {
                    ID = titel.ID.ToString(),
                    Bezeichnung = titel.Bezeichnung
                });
            }
            foreach (var wohnart in KreditVerwaltung.WohnartenLaden())
            {
                alleWohnartAngaben.Add(new WohnartModel()
                {
                    ID = wohnart.ID.ToString(),
                    Bezeichnung = wohnart.Bezeichnung
                });
            }


            PersönlicheDatenModel model = new PersönlicheDatenModel()
            {
                AlleBildungsangaben = alleBildungsAngaben,
                AlleFamilienstandangaben = alleFamilienStandAngaben,
                AlleIdentifikationsangaben = alleIdentifikationsangaben,
                AlleStaatsbuergerschaftsangaben = alleStaatsbuergerschaftsAngaben,
                AlleTitelangaben = alleTitelAngaben,
                AlleWohnartangaben = alleWohnartAngaben,

[DB-AG] Online_Kredit/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

[DB-AG] Online_Kredit/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

[DB-AG] Online_Kredit/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}


<!--top nav end here-->
<!--banner start here-->
<div class="banner">
</div>
<!--banner end here-->
<!--about-->
<div class="about" id="about">
    <div class="container">
        <div class="col-md-4 about-left">
            <div class="ab-top">
                <h3>Infinitus Kredit</h3>
                <p>Hier geht es rasch und unkompliziert @Html.ActionLink("zum Wunschkredit", "KreditRechner", "Kredit").</p>
                @*<a href="#" data-toggle="modal" data-target="#myModal">Mehr Informationen</a>*@
            </div>
        </div>
        <div class="col-md-8 about-right">
            <h3>Einfach Online Kredit</h3>
            <div class="col-md-12 ab-lft">
                <h4>Sicher & Schnell</h4>
                <p>
                    Egal ob neue Einrichtung, ein Wellnessurlaub, Weiterbildung oder Geschenke für Ihre Mitmenschen - Sie können all Ihre Wünsche mit dem Infinitus Kredit ganz einfach erfüllen!
                    <br /><br />
                    Laut einer Studie sind Menschen die ihre sehnlichsten Wünsche erfüllen, viel glücklicher und zufriedener mit ihrem Leben. Wünsche kosten leider, doch Ihre Infinitus Bank steht Ihnen jederzeit mit einem Kredit zur Verfügung.
                    <br /><br />
                    Weitere Fragen zum Kredit können Sie an folgende E-Mail Adresse schicken<br />
                     <a class="link" href="infinitus@banking.com">infinitus@banking.com</a>
                </p>
            </div>
            </div>
        </div>
    </div>
<!--about-->
<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Pellentesque vehicula</h4>
            </div>
            <div class="modal-body">
                <p>In varius sem id aliquet rutrum. Pellentesque ut neque ligula. Fusce dapibus volutpat magna, ac feugiat dolor bibendum et. Integer dignissim gravida nunc, eget hendrerit enim. Quisque dapibus mollis finibus. Curabitur nulla enim, aliquet ac ultricies luctus, lacinia ut felis. Etiam aliquam massa nec lorem pulvinar porttitor. Maecenas in rutrum purus, eget consectetur arcu. Sed id pretium ligula, id hendrerit nunc. Nam ut tincidunt erat, sit amet accumsan risus..</p>
            </div>
        </div>
    </div>
</div>
<!--// Modal -->